use NotflixDB;
SET session sql_mode='NO_BACKSLASH_ESCAPES';
insert into episode values(10,4,0,'','1h',0,'http://notflix.com');
insert into episode values(10,4,1,'','45m',0,'http://notflix.com');
insert into episode values(10,4,2,'','45m',0,'http://notflix.com');
insert into episode values(10,4,3,'','45m',0,'http://notflix.com');
insert into episode values(10,4,4,'','45m',0,'http://notflix.com');
insert into episode values(10,4,5,'','45m',0,'http://notflix.com');
insert into episode values(10,4,6,'','45m',0,'http://notflix.com');
insert into episode values(10,4,7,"",'45m',0,'http://notflix.com');
insert into episode values(10,4,8,"",'45m',0,'http://notflix.com');
insert into episode values(10,4,9,'','45m',0,'http://notflix.com');
insert into episode values(10,4,10,'','45m',0,'http://notflix.com');
insert into episode values(10,4,11,'','45m',0,'http://notflix.com');
insert into episode values(10,4,12,'','45m',0,'http://notflix.com');
insert into episode values(10,4,13,'','45m',0,'http://notflix.com');
select * from episode where SeriesID = 10 and SeasonID = 4;
